/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Application : Metadata about the application



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Application {
    /// This field will map to the application ID that is returned from /item/applications/list, or provided to the institution in an oauth redirect.
    #[serde(rename = "application_id")]
    pub application_id: String,
    /// The name of the application
    #[serde(rename = "name")]
    pub name: String,
    /// The date this application was linked in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) (YYYY-MM-DD) format in UTC.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// The date this application was granted production access at Plaid in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) (YYYY-MM-DD) format in UTC.
    #[serde(rename = "join_date")]
    pub join_date: String,
    /// A URL that links to the application logo image.
    #[serde(rename = "logo_url")]
    pub logo_url: Option<String>,
    /// The URL for the application's website
    #[serde(rename = "application_url")]
    pub application_url: Option<String>,
    /// A string provided by the connected app stating why they use their respective enabled products.
    #[serde(rename = "reason_for_access")]
    pub reason_for_access: Option<String>,
}

impl Application {
    /// Metadata about the application
    pub fn new(application_id: String, name: String, join_date: String, logo_url: Option<String>, application_url: Option<String>, reason_for_access: Option<String>) -> Application {
        Application {
            application_id,
            name,
            created_at: None,
            join_date,
            logo_url,
            application_url,
            reason_for_access,
        }
    }
}


