/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AssetReportTransactionAllOf {
    /// The date on which the transaction took place, in IS0 8601 format.
    #[serde(rename = "date_transacted", skip_serializing_if = "Option::is_none")]
    pub date_transacted: Option<String>,
}

impl AssetReportTransactionAllOf {
    pub fn new() -> AssetReportTransactionAllOf {
        AssetReportTransactionAllOf {
            date_transacted: None,
        }
    }
}


