/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Cause : An error object and associated `item_id` used to identify a specific Item and error when a batch operation operating on multiple Items has encountered an error in one of the Items.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Cause {
    /// The `item_id` of the Item associated with this webhook, warning, or error
    #[serde(rename = "item_id")]
    pub item_id: String,
    #[serde(rename = "error")]
    pub error: Box<crate::models::PlaidError>,
}

impl Cause {
    /// An error object and associated `item_id` used to identify a specific Item and error when a batch operation operating on multiple Items has encountered an error in one of the Items.
    pub fn new(item_id: String, error: crate::models::PlaidError) -> Cause {
        Cause {
            item_id,
            error: Box::new(error),
        }
    }
}


