/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DistributionBreakdown : Information about the accounts that the payment was distributed to.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DistributionBreakdown {
    /// Name of the account for the given distribution.
    #[serde(rename = "account_name", skip_serializing_if = "Option::is_none")]
    pub account_name: Option<String>,
    /// The name of the bank that the payment is being deposited to.
    #[serde(rename = "bank_name", skip_serializing_if = "Option::is_none")]
    pub bank_name: Option<String>,
    /// The amount distributed to this account.
    #[serde(rename = "current_amount", skip_serializing_if = "Option::is_none")]
    pub current_amount: Option<f32>,
    /// The ISO-4217 currency code of the net pay. Always `null` if `unofficial_currency_code` is non-null.
    #[serde(rename = "iso_currency_code", skip_serializing_if = "Option::is_none")]
    pub iso_currency_code: Option<String>,
    /// The last 2-4 alphanumeric characters of an account's official account number.
    #[serde(rename = "mask", skip_serializing_if = "Option::is_none")]
    pub mask: Option<String>,
    /// Type of the account that the paystub was sent to (e.g. 'checking').
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    /// The unofficial currency code associated with the net pay. Always `null` if `iso_currency_code` is non-`null`. Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.  See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `iso_currency_code`s.
    #[serde(rename = "unofficial_currency_code", skip_serializing_if = "Option::is_none")]
    pub unofficial_currency_code: Option<String>,
    #[serde(rename = "current_pay", skip_serializing_if = "Option::is_none")]
    pub current_pay: Option<crate::models::Pay>,
}

impl DistributionBreakdown {
    /// Information about the accounts that the payment was distributed to.
    pub fn new() -> DistributionBreakdown {
        DistributionBreakdown {
            account_name: None,
            bank_name: None,
            current_amount: None,
            iso_currency_code: None,
            mask: None,
            _type: None,
            unofficial_currency_code: None,
            current_pay: None,
        }
    }
}


