/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DocumentMetadata : An object representing metadata from the end user's uploaded document.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentMetadata {
    /// The name of the document.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The processing status of the document.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// An identifier of the document that is also present in the paystub response.
    #[serde(rename = "doc_id", skip_serializing_if = "Option::is_none")]
    pub doc_id: Option<String>,
    #[serde(rename = "doc_type", skip_serializing_if = "Option::is_none")]
    pub doc_type: Option<crate::models::DocType>,
}

impl DocumentMetadata {
    /// An object representing metadata from the end user's uploaded document.
    pub fn new() -> DocumentMetadata {
        DocumentMetadata {
            name: None,
            status: None,
            doc_id: None,
            doc_type: None,
        }
    }
}


