/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EarningsBreakdownCanonicalDescription : Commonly used term to describe the earning line item.

/// Commonly used term to describe the earning line item.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EarningsBreakdownCanonicalDescription {
    #[serde(rename = "BONUS")]
    BONUS,
    #[serde(rename = "COMMISSION")]
    COMMISSION,
    #[serde(rename = "OVERTIME")]
    OVERTIME,
    #[serde(rename = "PAID TIME OFF")]
    PAIDTIMEOFF,
    #[serde(rename = "REGULAR PAY")]
    REGULARPAY,
    #[serde(rename = "VACATION")]
    VACATION,
    #[serde(rename = "BASIC ALLOWANCE HOUSING")]
    BASICALLOWANCEHOUSING,
    #[serde(rename = "BASIC ALLOWANCE SUBSISTENCE")]
    BASICALLOWANCESUBSISTENCE,
    #[serde(rename = "OTHER")]
    OTHER,
    #[serde(rename = "null")]
    Null,

}

impl ToString for EarningsBreakdownCanonicalDescription {
    fn to_string(&self) -> String {
        match self {
            Self::BONUS => String::from("BONUS"),
            Self::COMMISSION => String::from("COMMISSION"),
            Self::OVERTIME => String::from("OVERTIME"),
            Self::PAIDTIMEOFF => String::from("PAID TIME OFF"),
            Self::REGULARPAY => String::from("REGULAR PAY"),
            Self::VACATION => String::from("VACATION"),
            Self::BASICALLOWANCEHOUSING => String::from("BASIC ALLOWANCE HOUSING"),
            Self::BASICALLOWANCESUBSISTENCE => String::from("BASIC ALLOWANCE SUBSISTENCE"),
            Self::OTHER => String::from("OTHER"),
            Self::Null => String::from("null"),
        }
    }
}

impl Default for EarningsBreakdownCanonicalDescription {
    fn default() -> EarningsBreakdownCanonicalDescription {
        Self::BONUS
    }
}




