/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Employee : Data about the employee.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Employee {
    #[serde(rename = "address")]
    pub address: crate::models::PaystubAddress,
    /// The name of the employee.
    #[serde(rename = "name")]
    pub name: Option<String>,
    /// Marital status of the employee - either `single` or `married`.
    #[serde(rename = "marital_status", skip_serializing_if = "Option::is_none")]
    pub marital_status: Option<String>,
    #[serde(rename = "taxpayer_id", skip_serializing_if = "Option::is_none")]
    pub taxpayer_id: Option<crate::models::TaxpayerId>,
}

impl Employee {
    /// Data about the employee.
    pub fn new(address: crate::models::PaystubAddress, name: Option<String>) -> Employee {
        Employee {
            address,
            name,
            marital_status: None,
            taxpayer_id: None,
        }
    }
}


