/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// HoldingsDefaultUpdateWebhook : Fired when new or updated holdings have been detected on an investment account. The webhook typically fires once per day, after market close, in response to any newly added holdings or price changes to existing holdings.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HoldingsDefaultUpdateWebhook {
    /// `HOLDINGS`
    #[serde(rename = "webhook_type")]
    pub webhook_type: String,
    /// `DEFAULT_UPDATE`
    #[serde(rename = "webhook_code")]
    pub webhook_code: String,
    /// The `item_id` of the Item associated with this webhook, warning, or error
    #[serde(rename = "item_id")]
    pub item_id: String,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<crate::models::PlaidError>>,
    /// The number of new holdings reported since the last time this webhook was fired.
    #[serde(rename = "new_holdings")]
    pub new_holdings: f32,
    /// The number of updated holdings reported since the last time this webhook was fired.
    #[serde(rename = "updated_holdings")]
    pub updated_holdings: f32,
}

impl HoldingsDefaultUpdateWebhook {
    /// Fired when new or updated holdings have been detected on an investment account. The webhook typically fires once per day, after market close, in response to any newly added holdings or price changes to existing holdings.
    pub fn new(webhook_type: String, webhook_code: String, item_id: String, new_holdings: f32, updated_holdings: f32) -> HoldingsDefaultUpdateWebhook {
        HoldingsDefaultUpdateWebhook {
            webhook_type,
            webhook_code,
            item_id,
            error: None,
            new_holdings,
            updated_holdings,
        }
    }
}


