/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IncomeVerificationSummaryGetResponse : IncomeVerificationSummaryGetResponse defines the response schema for `/income/verification/summary/get`.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncomeVerificationSummaryGetResponse {
    /// A list of income summaries.
    #[serde(rename = "income_summaries")]
    pub income_summaries: Vec<crate::models::IncomeSummary>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<crate::models::PlaidError>>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl IncomeVerificationSummaryGetResponse {
    /// IncomeVerificationSummaryGetResponse defines the response schema for `/income/verification/summary/get`.
    pub fn new(income_summaries: Vec<crate::models::IncomeSummary>, request_id: String) -> IncomeVerificationSummaryGetResponse {
        IncomeVerificationSummaryGetResponse {
            income_summaries,
            error: None,
            request_id,
        }
    }
}


