/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IncomeVerificationPrecheckUser : Information about the user whose eligibility is being evaluated.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncomeVerificationPrecheckUser {
    /// The user's first name
    #[serde(rename = "first_name", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// The user's last name
    #[serde(rename = "last_name", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    /// The user's email address
    #[serde(rename = "email_address", skip_serializing_if = "Option::is_none")]
    pub email_address: Option<String>,
    #[serde(rename = "home_address", skip_serializing_if = "Option::is_none")]
    pub home_address: Option<crate::models::SignalAddressData>,
}

impl IncomeVerificationPrecheckUser {
    /// Information about the user whose eligibility is being evaluated.
    pub fn new() -> IncomeVerificationPrecheckUser {
        IncomeVerificationPrecheckUser {
            first_name: None,
            last_name: None,
            email_address: None,
            home_address: None,
        }
    }
}


