/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IncomeVerificationPaystubGetResponse : IncomeVerificationPaystubGetResponse defines the response schema for `/income/verification/paystub/get`.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncomeVerificationPaystubGetResponse {
    #[serde(rename = "paystub")]
    pub paystub: crate::models::Paystub,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<crate::models::PlaidError>>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl IncomeVerificationPaystubGetResponse {
    /// IncomeVerificationPaystubGetResponse defines the response schema for `/income/verification/paystub/get`.
    pub fn new(paystub: crate::models::Paystub, request_id: String) -> IncomeVerificationPaystubGetResponse {
        IncomeVerificationPaystubGetResponse {
            paystub,
            error: None,
            request_id,
        }
    }
}


