/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IncomeVerificationRefreshResponse : IncomeVerificationRequestResponse defines the response schema for `/income/verification/refresh`



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncomeVerificationRefreshResponse {
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
    #[serde(rename = "verification_refresh_status")]
    pub verification_refresh_status: crate::models::VerificationRefreshStatus,
}

impl IncomeVerificationRefreshResponse {
    /// IncomeVerificationRequestResponse defines the response schema for `/income/verification/refresh`
    pub fn new(request_id: String, verification_refresh_status: crate::models::VerificationRefreshStatus) -> IncomeVerificationRefreshResponse {
        IncomeVerificationRefreshResponse {
            request_id,
            verification_refresh_status,
        }
    }
}


