/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IncomeBreakdown : An object representing a breakdown of the different income types on the paystub.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncomeBreakdown {
    #[serde(rename = "type")]
    pub _type: Option<crate::models::IncomeBreakdownType>,
    /// The hourly rate at which the income is paid.
    #[serde(rename = "rate")]
    pub rate: Option<f32>,
    /// The number of hours logged for this income for this pay period.
    #[serde(rename = "hours")]
    pub hours: Option<f32>,
    /// The total pay for this pay period.
    #[serde(rename = "total")]
    pub total: Option<f32>,
}

impl IncomeBreakdown {
    /// An object representing a breakdown of the different income types on the paystub.
    pub fn new(_type: Option<crate::models::IncomeBreakdownType>, rate: Option<f32>, hours: Option<f32>, total: Option<f32>) -> IncomeBreakdown {
        IncomeBreakdown {
            _type,
            rate,
            hours,
            total,
        }
    }
}


