/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ItemStatusNullable : Information about the last successful and failed transactions update for the Item.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ItemStatusNullable {
    #[serde(rename = "investments", skip_serializing_if = "Option::is_none")]
    pub investments: Option<crate::models::ItemStatusInvestments>,
    #[serde(rename = "transactions", skip_serializing_if = "Option::is_none")]
    pub transactions: Option<crate::models::ItemStatusTransactions>,
    #[serde(rename = "last_webhook", skip_serializing_if = "Option::is_none")]
    pub last_webhook: Option<crate::models::ItemStatusLastWebhook>,
}

impl ItemStatusNullable {
    /// Information about the last successful and failed transactions update for the Item.
    pub fn new() -> ItemStatusNullable {
        ItemStatusNullable {
            investments: None,
            transactions: None,
            last_webhook: None,
        }
    }
}


