/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LinkTokenCreateRequestTransfer : Specifies options for initializing Link for use with the Transfer product.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LinkTokenCreateRequestTransfer {
    /// The `id` returned by the `/transfer/intent/create` endpoint.
    #[serde(rename = "intent_id", skip_serializing_if = "Option::is_none")]
    pub intent_id: Option<String>,
}

impl LinkTokenCreateRequestTransfer {
    /// Specifies options for initializing Link for use with the Transfer product.
    pub fn new() -> LinkTokenCreateRequestTransfer {
        LinkTokenCreateRequestTransfer {
            intent_id: None,
        }
    }
}


