/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LinkTokenCreateRequestPaymentInitiation : Specifies options for initializing Link for use with the Payment Initiation (Europe) product. This field is required if `payment_initiation` is included in the `products` array.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LinkTokenCreateRequestPaymentInitiation {
    /// The `payment_id` provided by the `/payment_initiation/payment/create` endpoint.
    #[serde(rename = "payment_id")]
    pub payment_id: String,
}

impl LinkTokenCreateRequestPaymentInitiation {
    /// Specifies options for initializing Link for use with the Payment Initiation (Europe) product. This field is required if `payment_initiation` is included in the `products` array.
    pub fn new(payment_id: String) -> LinkTokenCreateRequestPaymentInitiation {
        LinkTokenCreateRequestPaymentInitiation {
            payment_id,
        }
    }
}


