/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Meta : Allows specifying the metadata of the test account



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Meta {
    /// The account's name
    #[serde(rename = "name")]
    pub name: String,
    /// The account's official name
    #[serde(rename = "official_name")]
    pub official_name: String,
    /// The account's limit
    #[serde(rename = "limit")]
    pub limit: f32,
}

impl Meta {
    /// Allows specifying the metadata of the test account
    pub fn new(name: String, official_name: String, limit: f32) -> Meta {
        Meta {
            name,
            official_name,
            limit,
        }
    }
}


