/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PaymentInitiationPayment : PaymentInitiationPayment defines a payment initiation payment



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaymentInitiationPayment {
    /// The ID of the payment. Like all Plaid identifiers, the `payment_id` is case sensitive.
    #[serde(rename = "payment_id")]
    pub payment_id: String,
    #[serde(rename = "amount")]
    pub amount: crate::models::PaymentAmount,
    #[serde(rename = "status")]
    pub status: crate::models::PaymentInitiationPaymentStatus,
    /// The ID of the recipient
    #[serde(rename = "recipient_id")]
    pub recipient_id: String,
    /// A reference for the payment.
    #[serde(rename = "reference")]
    pub reference: String,
    /// The value of the reference sent to the bank after adjustment to pass bank validation rules.
    #[serde(rename = "adjusted_reference", skip_serializing_if = "Option::is_none")]
    pub adjusted_reference: Option<String>,
    /// The date and time of the last time the `status` was updated, in IS0 8601 format
    #[serde(rename = "last_status_update")]
    pub last_status_update: String,
    #[serde(rename = "schedule", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<Box<crate::models::ExternalPaymentScheduleGet>>,
    #[serde(rename = "refund_details", skip_serializing_if = "Option::is_none")]
    pub refund_details: Option<Box<crate::models::ExternalPaymentRefundDetails>>,
    #[serde(rename = "bacs")]
    pub bacs: Option<Box<crate::models::SenderBacsNullable>>,
    /// The International Bank Account Number (IBAN) for the sender, if specified in the `/payment_initiation/payment/create` call.
    #[serde(rename = "iban")]
    pub iban: Option<String>,
    /// Initiated refunds associated with the payment.
    #[serde(rename = "initiated_refunds", skip_serializing_if = "Option::is_none")]
    pub initiated_refunds: Option<Vec<crate::models::PaymentInitiationRefund>>,
    /// The EMI (E-Money Institution) wallet that this payment is associated with, if any. This wallet is used as an intermediary account to enable Plaid to reconcile the settlement of funds for Payment Initiation requests.
    #[serde(rename = "wallet_id", skip_serializing_if = "Option::is_none")]
    pub wallet_id: Option<String>,
    #[serde(rename = "scheme", skip_serializing_if = "Option::is_none")]
    pub scheme: Option<crate::models::PaymentScheme>,
    #[serde(rename = "adjusted_scheme", skip_serializing_if = "Option::is_none")]
    pub adjusted_scheme: Option<crate::models::PaymentScheme>,
}

impl PaymentInitiationPayment {
    /// PaymentInitiationPayment defines a payment initiation payment
    pub fn new(payment_id: String, amount: crate::models::PaymentAmount, status: crate::models::PaymentInitiationPaymentStatus, recipient_id: String, reference: String, last_status_update: String, bacs: Option<crate::models::SenderBacsNullable>, iban: Option<String>) -> PaymentInitiationPayment {
        PaymentInitiationPayment {
            payment_id,
            amount,
            status,
            recipient_id,
            reference,
            adjusted_reference: None,
            last_status_update,
            schedule: None,
            refund_details: None,
            bacs: Box::new(bacs),
            iban,
            initiated_refunds: None,
            wallet_id: None,
            scheme: None,
            adjusted_scheme: None,
        }
    }
}


