/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PaymentScheme : Payment scheme. If not specified - the default in the region will be used (e.g. `SEPA_CREDIT_TRANSFER` for EU). Using unsupported values will result in a failed payment.  `FASTER_PAYMENTS`: Enables payments to move quickly between UK bank accounts. Default value in the UK.  `SEPA_CREDIT_TRANSFER`: The standard payment to a beneficiary within the SEPA area.  `SEPA_CREDIT_TRANSFER_INSTANT`: Instant payment within the SEPA area. May involve additional fees and may not be available at some banks.

/// Payment scheme. If not specified - the default in the region will be used (e.g. `SEPA_CREDIT_TRANSFER` for EU). Using unsupported values will result in a failed payment.  `FASTER_PAYMENTS`: Enables payments to move quickly between UK bank accounts. Default value in the UK.  `SEPA_CREDIT_TRANSFER`: The standard payment to a beneficiary within the SEPA area.  `SEPA_CREDIT_TRANSFER_INSTANT`: Instant payment within the SEPA area. May involve additional fees and may not be available at some banks.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentScheme {
    #[serde(rename = "null")]
    Null,
    #[serde(rename = "FASTER_PAYMENTS")]
    FASTERPAYMENTS,
    #[serde(rename = "SEPA_CREDIT_TRANSFER")]
    SEPACREDITTRANSFER,
    #[serde(rename = "SEPA_CREDIT_TRANSFER_INSTANT")]
    SEPACREDITTRANSFERINSTANT,

}

impl ToString for PaymentScheme {
    fn to_string(&self) -> String {
        match self {
            Self::Null => String::from("null"),
            Self::FASTERPAYMENTS => String::from("FASTER_PAYMENTS"),
            Self::SEPACREDITTRANSFER => String::from("SEPA_CREDIT_TRANSFER"),
            Self::SEPACREDITTRANSFERINSTANT => String::from("SEPA_CREDIT_TRANSFER_INSTANT"),
        }
    }
}

impl Default for PaymentScheme {
    fn default() -> PaymentScheme {
        Self::Null
    }
}




