/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PaymentInitiationRecipientCreateRequest : PaymentInitiationRecipientCreateRequest defines the request schema for `/payment_initiation/recipient/create`



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaymentInitiationRecipientCreateRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// The name of the recipient
    #[serde(rename = "name")]
    pub name: String,
    /// The International Bank Account Number (IBAN) for the recipient. If BACS data is not provided, an IBAN is required.
    #[serde(rename = "iban", skip_serializing_if = "Option::is_none")]
    pub iban: Option<String>,
    #[serde(rename = "bacs", skip_serializing_if = "Option::is_none")]
    pub bacs: Option<Box<crate::models::RecipientBacsNullable>>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<crate::models::PaymentInitiationAddress>,
}

impl PaymentInitiationRecipientCreateRequest {
    /// PaymentInitiationRecipientCreateRequest defines the request schema for `/payment_initiation/recipient/create`
    pub fn new(name: String) -> PaymentInitiationRecipientCreateRequest {
        PaymentInitiationRecipientCreateRequest {
            client_id: None,
            secret: None,
            name,
            iban: None,
            bacs: None,
            address: None,
        }
    }
}


