/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PaymentInitiationPaymentCreateResponse : PaymentInitiationPaymentCreateResponse defines the response schema for `/payment_initiation/payment/create`



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaymentInitiationPaymentCreateResponse {
    /// A unique ID identifying the payment
    #[serde(rename = "payment_id")]
    pub payment_id: String,
    /// For a payment returned by this endpoint, there is only one possible value:  `PAYMENT_STATUS_INPUT_NEEDED`: The initial phase of the payment
    #[serde(rename = "status")]
    pub status: Status,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl PaymentInitiationPaymentCreateResponse {
    /// PaymentInitiationPaymentCreateResponse defines the response schema for `/payment_initiation/payment/create`
    pub fn new(payment_id: String, status: Status, request_id: String) -> PaymentInitiationPaymentCreateResponse {
        PaymentInitiationPaymentCreateResponse {
            payment_id,
            status,
            request_id,
        }
    }
}

/// For a payment returned by this endpoint, there is only one possible value:  `PAYMENT_STATUS_INPUT_NEEDED`: The initial phase of the payment
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "PAYMENT_STATUS_INPUT_NEEDED")]
    PAYMENTSTATUSINPUTNEEDED,
}

impl Default for Status {
    fn default() -> Status {
        Self::PAYMENTSTATUSINPUTNEEDED
    }
}

