/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PaystubVerificationStatus : Derived verification status.

/// Derived verification status.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaystubVerificationStatus {
    #[serde(rename = "PAYSTUB_VERIFICATION_STATUS_UNKNOWN")]
    PAYSTUBVERIFICATIONSTATUSUNKNOWN,
    #[serde(rename = "PAYSTUB_VERIFICATION_STATUS_VERIFIED")]
    PAYSTUBVERIFICATIONSTATUSVERIFIED,
    #[serde(rename = "PAYSTUB_VERIFICATION_STATUS_FRAUDULENT")]
    PAYSTUBVERIFICATIONSTATUSFRAUDULENT,
    #[serde(rename = "null")]
    Null,

}

impl ToString for PaystubVerificationStatus {
    fn to_string(&self) -> String {
        match self {
            Self::PAYSTUBVERIFICATIONSTATUSUNKNOWN => String::from("PAYSTUB_VERIFICATION_STATUS_UNKNOWN"),
            Self::PAYSTUBVERIFICATIONSTATUSVERIFIED => String::from("PAYSTUB_VERIFICATION_STATUS_VERIFIED"),
            Self::PAYSTUBVERIFICATIONSTATUSFRAUDULENT => String::from("PAYSTUB_VERIFICATION_STATUS_FRAUDULENT"),
            Self::Null => String::from("null"),
        }
    }
}

impl Default for PaystubVerificationStatus {
    fn default() -> PaystubVerificationStatus {
        Self::PAYSTUBVERIFICATIONSTATUSUNKNOWN
    }
}




