/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PaystubDeduction : Deduction on the paystub



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaystubDeduction {
    /// The description of the deduction, as provided on the paystub. For example: `\"401(k)\"`, `\"FICA MED TAX\"`.
    #[serde(rename = "type")]
    pub _type: Option<String>,
    /// `true` if the deduction is pre-tax; `false` otherwise.
    #[serde(rename = "is_pretax")]
    pub is_pretax: Option<bool>,
    /// The amount of the deduction.
    #[serde(rename = "total")]
    pub total: Option<f32>,
}

impl PaystubDeduction {
    /// Deduction on the paystub
    pub fn new(_type: Option<String>, is_pretax: Option<bool>, total: Option<f32>) -> PaystubDeduction {
        PaystubDeduction {
            _type,
            is_pretax,
            total,
        }
    }
}


