/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PersonalFinanceCategory : Information describing the intent of the transaction. Most relevant for personal finance use cases, but not limited to such use cases. The field is currently in beta.  The complete category can be generated by concatenating primary and detailed categories.  This feature is currently in beta – to request access, contact transactions-feedback@plaid.com.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PersonalFinanceCategory {
    /// A high level category that communicates the broad category of the transaction.
    #[serde(rename = "primary")]
    pub primary: String,
    /// Provides additional granularity to the primary categorization.
    #[serde(rename = "detailed")]
    pub detailed: String,
}

impl PersonalFinanceCategory {
    /// Information describing the intent of the transaction. Most relevant for personal finance use cases, but not limited to such use cases. The field is currently in beta.  The complete category can be generated by concatenating primary and detailed categories.  This feature is currently in beta – to request access, contact transactions-feedback@plaid.com.
    pub fn new(primary: String, detailed: String) -> PersonalFinanceCategory {
        PersonalFinanceCategory {
            primary,
            detailed,
        }
    }
}


