/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RequestedScopes : Scope of required and optional account features or content from a ConnectedApplication.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RequestedScopes {
    #[serde(rename = "account_filters", skip_serializing_if = "Option::is_none")]
    pub account_filters: Option<Box<crate::models::AccountFilter>>,
    #[serde(rename = "account_selection_cardinality")]
    pub account_selection_cardinality: crate::models::AccountSelectionCardinality,
}

impl RequestedScopes {
    /// Scope of required and optional account features or content from a ConnectedApplication.
    pub fn new(account_selection_cardinality: crate::models::AccountSelectionCardinality) -> RequestedScopes {
        RequestedScopes {
            account_filters: None,
            account_selection_cardinality,
        }
    }
}


