/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SandboxPublicTokenCreateRequestOptions : An optional set of options to be used when configuring the Item. If specified, must not be `null`.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SandboxPublicTokenCreateRequestOptions {
    /// Specify a webhook to associate with the new Item.
    #[serde(rename = "webhook", skip_serializing_if = "Option::is_none")]
    pub webhook: Option<String>,
    /// Test username to use for the creation of the Sandbox Item. Default value is `user_good`.
    #[serde(rename = "override_username", skip_serializing_if = "Option::is_none")]
    pub override_username: Option<String>,
    /// Test password to use for the creation of the Sandbox Item. Default value is `pass_good`.
    #[serde(rename = "override_password", skip_serializing_if = "Option::is_none")]
    pub override_password: Option<String>,
    #[serde(rename = "transactions", skip_serializing_if = "Option::is_none")]
    pub transactions: Option<Box<crate::models::SandboxPublicTokenCreateRequestOptionsTransactions>>,
}

impl SandboxPublicTokenCreateRequestOptions {
    /// An optional set of options to be used when configuring the Item. If specified, must not be `null`.
    pub fn new() -> SandboxPublicTokenCreateRequestOptions {
        SandboxPublicTokenCreateRequestOptions {
            webhook: None,
            override_username: None,
            override_password: None,
            transactions: None,
        }
    }
}


