/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Security : Contains details about a security



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Security {
    /// A unique, Plaid-specific identifier for the security, used to associate securities with holdings. Like all Plaid identifiers, the `security_id` is case sensitive.
    #[serde(rename = "security_id")]
    pub security_id: String,
    /// 12-character ISIN, a globally unique securities identifier.
    #[serde(rename = "isin")]
    pub isin: Option<String>,
    /// 9-character CUSIP, an identifier assigned to North American securities.
    #[serde(rename = "cusip")]
    pub cusip: Option<String>,
    /// 7-character SEDOL, an identifier assigned to securities in the UK.
    #[serde(rename = "sedol")]
    pub sedol: Option<String>,
    /// An identifier given to the security by the institution
    #[serde(rename = "institution_security_id")]
    pub institution_security_id: Option<String>,
    /// If `institution_security_id` is present, this field indicates the Plaid `institution_id` of the institution to whom the identifier belongs.
    #[serde(rename = "institution_id")]
    pub institution_id: Option<String>,
    /// In certain cases, Plaid will provide the ID of another security whose performance resembles this security, typically when the original security has low volume, or when a private security can be modeled with a publicly traded security.
    #[serde(rename = "proxy_security_id")]
    pub proxy_security_id: Option<String>,
    /// A descriptive name for the security, suitable for display.
    #[serde(rename = "name")]
    pub name: Option<String>,
    /// The security’s trading symbol for publicly traded securities, and otherwise a short identifier if available.
    #[serde(rename = "ticker_symbol")]
    pub ticker_symbol: Option<String>,
    /// Indicates that a security is a highly liquid asset and can be treated like cash.
    #[serde(rename = "is_cash_equivalent")]
    pub is_cash_equivalent: Option<bool>,
    /// The security type of the holding. Valid security types are:  `cash`: Cash, currency, and money market funds  `derivative`: Options, warrants, and other derivative instruments  `equity`: Domestic and foreign equities  `etf`: Multi-asset exchange-traded investment funds  `fixed income`: Bonds and certificates of deposit (CDs)  `loan`: Loans and loan receivables.  `mutual fund`: Open- and closed-end vehicles pooling funds of multiple investors.  `other`: Unknown or other investment types
    #[serde(rename = "type")]
    pub _type: Option<String>,
    /// Price of the security at the close of the previous trading session. `null` for non-public securities. If the security is a foreign currency or a cryptocurrency this field will be updated daily and will be priced in USD.
    #[serde(rename = "close_price")]
    pub close_price: Option<f32>,
    /// Date for which `close_price` is accurate. Always `null` if `close_price` is `null`.
    #[serde(rename = "close_price_as_of")]
    pub close_price_as_of: Option<String>,
    /// The ISO-4217 currency code of the price given. Always `null` if `unofficial_currency_code` is non-`null`.
    #[serde(rename = "iso_currency_code")]
    pub iso_currency_code: Option<String>,
    /// The unofficial currency code associated with the security. Always `null` if `iso_currency_code` is non-`null`. Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.  See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `iso_currency_code`s.
    #[serde(rename = "unofficial_currency_code")]
    pub unofficial_currency_code: Option<String>,
}

impl Security {
    /// Contains details about a security
    pub fn new(security_id: String, isin: Option<String>, cusip: Option<String>, sedol: Option<String>, institution_security_id: Option<String>, institution_id: Option<String>, proxy_security_id: Option<String>, name: Option<String>, ticker_symbol: Option<String>, is_cash_equivalent: Option<bool>, _type: Option<String>, close_price: Option<f32>, close_price_as_of: Option<String>, iso_currency_code: Option<String>, unofficial_currency_code: Option<String>) -> Security {
        Security {
            security_id,
            isin,
            cusip,
            sedol,
            institution_security_id,
            institution_id,
            proxy_security_id,
            name,
            ticker_symbol,
            is_cash_equivalent,
            _type,
            close_price,
            close_price_as_of,
            iso_currency_code,
            unofficial_currency_code,
        }
    }
}


