/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SignalEvaluateRequest : SignalEvaluateRequest defines the request schema for `/signal/evaluate`



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SignalEvaluateRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// The access token associated with the Item data is being requested for.
    #[serde(rename = "access_token")]
    pub access_token: String,
    /// The `account_id` of the account whose verification status is to be modified
    #[serde(rename = "account_id")]
    pub account_id: String,
    /// The unique ID that you would like to use to refer to this transaction. For your convenience mapping your internal data, you could use your internal ID/identifier for this transaction. The max length for this field is 36 characters.
    #[serde(rename = "client_transaction_id")]
    pub client_transaction_id: String,
    /// The transaction amount, in USD (e.g. `102.05`)
    #[serde(rename = "amount")]
    pub amount: f32,
    /// `true` if the end user is present while initiating the ACH transfer and the endpoint is being called; `false` otherwise (for example, when the ACH transfer is scheduled and the end user is not present, or you call this endpoint after the ACH transfer but before submitting the Nacha file for ACH processing).
    #[serde(rename = "user_present", skip_serializing_if = "Option::is_none")]
    pub user_present: Option<bool>,
    /// A unique ID that identifies the end user in your system. This ID is used to correlate requests by a user with multiple Items. The max length for this field is 36 characters.
    #[serde(rename = "client_user_id", skip_serializing_if = "Option::is_none")]
    pub client_user_id: Option<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<crate::models::SignalUser>>,
    #[serde(rename = "device", skip_serializing_if = "Option::is_none")]
    pub device: Option<Box<crate::models::SignalDevice>>,
}

impl SignalEvaluateRequest {
    /// SignalEvaluateRequest defines the request schema for `/signal/evaluate`
    pub fn new(access_token: String, account_id: String, client_transaction_id: String, amount: f32) -> SignalEvaluateRequest {
        SignalEvaluateRequest {
            client_id: None,
            secret: None,
            access_token,
            account_id,
            client_transaction_id,
            amount,
            user_present: None,
            client_user_id: None,
            user: None,
            device: None,
        }
    }
}


