/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// StudentLoan : Contains details about a student loan account



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StudentLoan {
    /// The ID of the account that this liability belongs to.
    #[serde(rename = "account_id")]
    pub account_id: Option<String>,
    /// The account number of the loan. For some institutions, this may be a masked version of the number (e.g., the last 4 digits instead of the entire number).
    #[serde(rename = "account_number")]
    pub account_number: Option<String>,
    /// The dates on which loaned funds were disbursed or will be disbursed. These are often in the past. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
    #[serde(rename = "disbursement_dates")]
    pub disbursement_dates: Option<Vec<String>>,
    /// The date when the student loan is expected to be paid off. Availability for this field is limited. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
    #[serde(rename = "expected_payoff_date")]
    pub expected_payoff_date: Option<String>,
    /// The guarantor of the student loan.
    #[serde(rename = "guarantor")]
    pub guarantor: Option<String>,
    /// The interest rate on the loan as a percentage.
    #[serde(rename = "interest_rate_percentage")]
    pub interest_rate_percentage: f32,
    /// `true` if a payment is currently overdue. Availability for this field is limited.
    #[serde(rename = "is_overdue")]
    pub is_overdue: Option<bool>,
    /// The amount of the last payment.
    #[serde(rename = "last_payment_amount")]
    pub last_payment_amount: Option<f32>,
    /// The date of the last payment. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
    #[serde(rename = "last_payment_date")]
    pub last_payment_date: Option<String>,
    /// The date of the last statement. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
    #[serde(rename = "last_statement_issue_date")]
    pub last_statement_issue_date: Option<String>,
    /// The type of loan, e.g., \"Consolidation Loans\".
    #[serde(rename = "loan_name")]
    pub loan_name: Option<String>,
    #[serde(rename = "loan_status")]
    pub loan_status: crate::models::StudentLoanStatus,
    /// The minimum payment due for the next billing cycle. There are some exceptions: Some institutions require a minimum payment across all loans associated with an account number. Our API presents that same minimum payment amount on each loan. The institutions that do this are: Great Lakes ( `ins_116861`), Firstmark (`ins_116295`), Commonbond Firstmark Services (`ins_116950`), Nelnet (`ins_116528`), EdFinancial Services (`ins_116304`), Granite State (`ins_116308`), and Oklahoma Student Loan Authority (`ins_116945`). Firstmark (`ins_116295` ) and Navient (`ins_116248`) will display as $0 if there is an autopay program in effect.
    #[serde(rename = "minimum_payment_amount")]
    pub minimum_payment_amount: Option<f32>,
    /// The due date for the next payment. The due date is `null` if a payment is not expected. A payment is not expected if `loan_status.type` is `deferment`, `in_school`, `consolidated`, `paid in full`, or `transferred`. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
    #[serde(rename = "next_payment_due_date")]
    pub next_payment_due_date: Option<String>,
    /// The date on which the loan was initially lent. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD). 
    #[serde(rename = "origination_date")]
    pub origination_date: Option<String>,
    /// The original principal balance of the loan.
    #[serde(rename = "origination_principal_amount")]
    pub origination_principal_amount: Option<f32>,
    /// The total dollar amount of the accrued interest balance. For Sallie Mae ( `ins_116944`), this amount is included in the current balance of the loan, so this field will return as `null`.
    #[serde(rename = "outstanding_interest_amount")]
    pub outstanding_interest_amount: Option<f32>,
    /// The relevant account number that should be used to reference this loan for payments. In the majority of cases, `payment_reference_number` will match a`ccount_number,` but in some institutions, such as Great Lakes (`ins_116861`), it will be different.
    #[serde(rename = "payment_reference_number")]
    pub payment_reference_number: Option<String>,
    #[serde(rename = "pslf_status")]
    pub pslf_status: crate::models::PslfStatus,
    #[serde(rename = "repayment_plan")]
    pub repayment_plan: crate::models::StudentRepaymentPlan,
    /// The sequence number of the student loan. Heartland ECSI (`ins_116948`) does not make this field available.
    #[serde(rename = "sequence_number")]
    pub sequence_number: Option<String>,
    #[serde(rename = "servicer_address")]
    pub servicer_address: crate::models::ServicerAddressData,
    /// The year to date (YTD) interest paid. Availability for this field is limited.
    #[serde(rename = "ytd_interest_paid")]
    pub ytd_interest_paid: Option<f32>,
    /// The year to date (YTD) principal paid. Availability for this field is limited.
    #[serde(rename = "ytd_principal_paid")]
    pub ytd_principal_paid: Option<f32>,
}

impl StudentLoan {
    /// Contains details about a student loan account
    pub fn new(account_id: Option<String>, account_number: Option<String>, disbursement_dates: Option<Vec<String>>, expected_payoff_date: Option<String>, guarantor: Option<String>, interest_rate_percentage: f32, is_overdue: Option<bool>, last_payment_amount: Option<f32>, last_payment_date: Option<String>, last_statement_issue_date: Option<String>, loan_name: Option<String>, loan_status: crate::models::StudentLoanStatus, minimum_payment_amount: Option<f32>, next_payment_due_date: Option<String>, origination_date: Option<String>, origination_principal_amount: Option<f32>, outstanding_interest_amount: Option<f32>, payment_reference_number: Option<String>, pslf_status: crate::models::PslfStatus, repayment_plan: crate::models::StudentRepaymentPlan, sequence_number: Option<String>, servicer_address: crate::models::ServicerAddressData, ytd_interest_paid: Option<f32>, ytd_principal_paid: Option<f32>) -> StudentLoan {
        StudentLoan {
            account_id,
            account_number,
            disbursement_dates,
            expected_payoff_date,
            guarantor,
            interest_rate_percentage,
            is_overdue,
            last_payment_amount,
            last_payment_date,
            last_statement_issue_date,
            loan_name,
            loan_status,
            minimum_payment_amount,
            next_payment_due_date,
            origination_date,
            origination_principal_amount,
            outstanding_interest_amount,
            payment_reference_number,
            pslf_status,
            repayment_plan,
            sequence_number,
            servicer_address,
            ytd_interest_paid,
            ytd_principal_paid,
        }
    }
}


