/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TotalCanonicalDescription : Commonly used term to describe the line item.

/// Commonly used term to describe the line item.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TotalCanonicalDescription {
    #[serde(rename = "BONUS")]
    BONUS,
    #[serde(rename = "COMMISSION")]
    COMMISSION,
    #[serde(rename = "OVERTIME")]
    OVERTIME,
    #[serde(rename = "PAID TIME OFF")]
    PAIDTIMEOFF,
    #[serde(rename = "REGULAR PAY")]
    REGULARPAY,
    #[serde(rename = "VACATION")]
    VACATION,
    #[serde(rename = "EMPLOYEE MEDICARE")]
    EMPLOYEEMEDICARE,
    #[serde(rename = "FICA")]
    FICA,
    #[serde(rename = "SOCIAL SECURITY EMPLOYEE TAX")]
    SOCIALSECURITYEMPLOYEETAX,
    #[serde(rename = "MEDICAL")]
    MEDICAL,
    #[serde(rename = "VISION")]
    VISION,
    #[serde(rename = "DENTAL")]
    DENTAL,
    #[serde(rename = "NET PAY")]
    NETPAY,
    #[serde(rename = "TAXES")]
    TAXES,
    #[serde(rename = "NOT_FOUND")]
    NOTFOUND,
    #[serde(rename = "OTHER")]
    OTHER,
    #[serde(rename = "null")]
    Null,

}

impl ToString for TotalCanonicalDescription {
    fn to_string(&self) -> String {
        match self {
            Self::BONUS => String::from("BONUS"),
            Self::COMMISSION => String::from("COMMISSION"),
            Self::OVERTIME => String::from("OVERTIME"),
            Self::PAIDTIMEOFF => String::from("PAID TIME OFF"),
            Self::REGULARPAY => String::from("REGULAR PAY"),
            Self::VACATION => String::from("VACATION"),
            Self::EMPLOYEEMEDICARE => String::from("EMPLOYEE MEDICARE"),
            Self::FICA => String::from("FICA"),
            Self::SOCIALSECURITYEMPLOYEETAX => String::from("SOCIAL SECURITY EMPLOYEE TAX"),
            Self::MEDICAL => String::from("MEDICAL"),
            Self::VISION => String::from("VISION"),
            Self::DENTAL => String::from("DENTAL"),
            Self::NETPAY => String::from("NET PAY"),
            Self::TAXES => String::from("TAXES"),
            Self::NOTFOUND => String::from("NOT_FOUND"),
            Self::OTHER => String::from("OTHER"),
            Self::Null => String::from("null"),
        }
    }
}

impl Default for TotalCanonicalDescription {
    fn default() -> TotalCanonicalDescription {
        Self::BONUS
    }
}




