/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransferAuthorizationDecisionRationale : The rationale for Plaid's decision regarding a proposed transfer. Will be null for `approved` decisions.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransferAuthorizationDecisionRationale {
    /// A code representing the rationale for permitting or declining the proposed transfer. Possible values are:  `NSF` – Transaction likely to result in a return due to insufficient funds.  `RISK` - Transaction is high-risk.  `MANUALLY_VERIFIED_ITEM` – Item created via same-day micro deposits, limited information available. Plaid can only offer `permitted` as a transaction decision.  `LOGIN_REQUIRED` – Unable to collect the account information required for an authorization decision due to Item staleness. Can be rectified using Link update mode.  `ERROR` – Unable to collect the account information required for an authorization decision due to an error.
    #[serde(rename = "code")]
    pub code: Code,
    /// A human-readable description of the code associated with a permitted transfer or transfer decline.
    #[serde(rename = "description")]
    pub description: String,
}

impl TransferAuthorizationDecisionRationale {
    /// The rationale for Plaid's decision regarding a proposed transfer. Will be null for `approved` decisions.
    pub fn new(code: Code, description: String) -> TransferAuthorizationDecisionRationale {
        TransferAuthorizationDecisionRationale {
            code,
            description,
        }
    }
}

/// A code representing the rationale for permitting or declining the proposed transfer. Possible values are:  `NSF` – Transaction likely to result in a return due to insufficient funds.  `RISK` - Transaction is high-risk.  `MANUALLY_VERIFIED_ITEM` – Item created via same-day micro deposits, limited information available. Plaid can only offer `permitted` as a transaction decision.  `LOGIN_REQUIRED` – Unable to collect the account information required for an authorization decision due to Item staleness. Can be rectified using Link update mode.  `ERROR` – Unable to collect the account information required for an authorization decision due to an error.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "NSF")]
    NSF,
    #[serde(rename = "RISK")]
    RISK,
    #[serde(rename = "MANUALLY_VERIFIED_ITEM")]
    MANUALLYVERIFIEDITEM,
    #[serde(rename = "LOGIN_REQUIRED")]
    LOGINREQUIRED,
    #[serde(rename = "ERROR")]
    ERROR,
}

impl Default for Code {
    fn default() -> Code {
        Self::NSF
    }
}

