/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransferIntentCreateRequest : Defines the request schema for `/transfer/intent/create`



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransferIntentCreateRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id")]
    pub client_id: String,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret")]
    pub secret: String,
    /// The Plaid `account_id` for the account that will be debited or credited.
    #[serde(rename = "account_id", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "mode")]
    pub mode: crate::models::TransferIntentCreateMode,
    /// The amount of the transfer (decimal string with two digits of precision e.g. \"10.00\").
    #[serde(rename = "amount")]
    pub amount: String,
    /// A description for the underlying transfer. Maximum of 8 characters.
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "ach_class")]
    pub ach_class: crate::models::AchClass,
    /// Plaid’s unique identifier for the origination account for the intent. If not provided, the default account will be used.
    #[serde(rename = "origination_account_id", skip_serializing_if = "Option::is_none")]
    pub origination_account_id: Option<String>,
    #[serde(rename = "user")]
    pub user: crate::models::TransferUserInRequest,
    /// The Metadata object is a mapping of client-provided string fields to any string value. The following limitations apply: - The JSON values must be Strings (no nested JSON objects allowed) - Only ASCII characters may be used - Maximum of 50 key/value pairs - Maximum key length of 40 characters - Maximum value length of 500 characters 
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<::std::collections::HashMap<String, String>>,
    /// The currency of the transfer amount, e.g. \"USD\"
    #[serde(rename = "iso_currency_code", skip_serializing_if = "Option::is_none")]
    pub iso_currency_code: Option<String>,
}

impl TransferIntentCreateRequest {
    /// Defines the request schema for `/transfer/intent/create`
    pub fn new(client_id: String, secret: String, mode: crate::models::TransferIntentCreateMode, amount: String, description: String, ach_class: crate::models::AchClass, user: crate::models::TransferUserInRequest) -> TransferIntentCreateRequest {
        TransferIntentCreateRequest {
            client_id,
            secret,
            account_id: None,
            mode,
            amount,
            description,
            ach_class,
            origination_account_id: None,
            user,
            metadata: None,
            iso_currency_code: None,
        }
    }
}


