/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransferAuthorizationGuaranteeDecisionRationale : The rationale for Plaid's decision to not guarantee a transfer. Will be `null` unless `guarantee_decision` is `NOT_GUARANTEED`.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransferAuthorizationGuaranteeDecisionRationale {
    /// A code representing the reason Plaid declined to guarantee this transfer:  `RETURN_BANK`: The risk of a bank-initiated return (for example, an R01/NSF) is too high to guarantee this transfer.  `RETURN_CUSTOMER`: The risk of a customer-initiated return (for example, a R10/Unauthorized) is too high to guarantee this transfer.  `GUARANTEE_LIMIT_REACHED`: This transfer is low-risk, but Guaranteed ACH has exhausted an internal limit on the number or rate of guarantees that applies to this transfer.  `RISK_ESTIMATE_UNAVAILABLE`: A risk estimate is unavailable for this Item.
    #[serde(rename = "code")]
    pub code: Code,
    /// A human-readable description of why the transfer cannot be guaranteed.
    #[serde(rename = "description")]
    pub description: String,
}

impl TransferAuthorizationGuaranteeDecisionRationale {
    /// The rationale for Plaid's decision to not guarantee a transfer. Will be `null` unless `guarantee_decision` is `NOT_GUARANTEED`.
    pub fn new(code: Code, description: String) -> TransferAuthorizationGuaranteeDecisionRationale {
        TransferAuthorizationGuaranteeDecisionRationale {
            code,
            description,
        }
    }
}

/// A code representing the reason Plaid declined to guarantee this transfer:  `RETURN_BANK`: The risk of a bank-initiated return (for example, an R01/NSF) is too high to guarantee this transfer.  `RETURN_CUSTOMER`: The risk of a customer-initiated return (for example, a R10/Unauthorized) is too high to guarantee this transfer.  `GUARANTEE_LIMIT_REACHED`: This transfer is low-risk, but Guaranteed ACH has exhausted an internal limit on the number or rate of guarantees that applies to this transfer.  `RISK_ESTIMATE_UNAVAILABLE`: A risk estimate is unavailable for this Item.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "RETURN_BANK")]
    RETURNBANK,
    #[serde(rename = "RETURN_CUSTOMER")]
    RETURNCUSTOMER,
    #[serde(rename = "GUARANTEE_LIMIT_REACHED")]
    GUARANTEELIMITREACHED,
    #[serde(rename = "RISK_ESTIMATE_UNAVAILABLE")]
    RISKESTIMATEUNAVAILABLE,
}

impl Default for Code {
    fn default() -> Code {
        Self::RETURNBANK
    }
}

