/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransferUserAddressInResponse : The address associated with the account holder.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransferUserAddressInResponse {
    /// The street number and name (i.e., \"100 Market St.\").
    #[serde(rename = "street")]
    pub street: Option<String>,
    /// Ex. \"San Francisco\"
    #[serde(rename = "city")]
    pub city: Option<String>,
    /// The state or province (e.g., \"California\").
    #[serde(rename = "region")]
    pub region: Option<String>,
    /// The postal code (e.g., \"94103\").
    #[serde(rename = "postal_code")]
    pub postal_code: Option<String>,
    /// A two-letter country code (e.g., \"US\").
    #[serde(rename = "country")]
    pub country: Option<String>,
}

impl TransferUserAddressInResponse {
    /// The address associated with the account holder.
    pub fn new(street: Option<String>, city: Option<String>, region: Option<String>, postal_code: Option<String>, country: Option<String>) -> TransferUserAddressInResponse {
        TransferUserAddressInResponse {
            street,
            city,
            region,
            postal_code,
            country,
        }
    }
}


