/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransferEventListRequest : Defines the request schema for `/transfer/event/list`



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransferEventListRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// The start datetime of transfers to list. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`)
    #[serde(rename = "start_date", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    /// The end datetime of transfers to list. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`)
    #[serde(rename = "end_date", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    /// Plaid’s unique identifier for a transfer.
    #[serde(rename = "transfer_id", skip_serializing_if = "Option::is_none")]
    pub transfer_id: Option<String>,
    /// The account ID to get events for all transactions to/from an account.
    #[serde(rename = "account_id", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    /// The type of transfer. This will be either `debit` or `credit`.  A `debit` indicates a transfer of money into your origination account; a `credit` indicates a transfer of money out of your origination account.
    #[serde(rename = "transfer_type", skip_serializing_if = "Option::is_none")]
    pub transfer_type: Option<TransferType>,
    /// Filter events by event type.
    #[serde(rename = "event_types", skip_serializing_if = "Option::is_none")]
    pub event_types: Option<Vec<crate::models::TransferEventType>>,
    /// Plaid’s unique identifier for a sweep.
    #[serde(rename = "sweep_id", skip_serializing_if = "Option::is_none")]
    pub sweep_id: Option<String>,
    /// The maximum number of transfer events to return. If the number of events matching the above parameters is greater than `count`, the most recent events will be returned.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The offset into the list of transfer events. When `count`=25 and `offset`=0, the first 25 events will be returned. When `count`=25 and `offset`=25, the next 25 bank transfer events will be returned.
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    /// The origination account ID to get events for transfers from a specific origination account.
    #[serde(rename = "origination_account_id", skip_serializing_if = "Option::is_none")]
    pub origination_account_id: Option<String>,
}

impl TransferEventListRequest {
    /// Defines the request schema for `/transfer/event/list`
    pub fn new() -> TransferEventListRequest {
        TransferEventListRequest {
            client_id: None,
            secret: None,
            start_date: None,
            end_date: None,
            transfer_id: None,
            account_id: None,
            transfer_type: None,
            event_types: None,
            sweep_id: None,
            count: None,
            offset: None,
            origination_account_id: None,
        }
    }
}

/// The type of transfer. This will be either `debit` or `credit`.  A `debit` indicates a transfer of money into your origination account; a `credit` indicates a transfer of money out of your origination account.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransferType {
    #[serde(rename = "debit")]
    Debit,
    #[serde(rename = "credit")]
    Credit,
    #[serde(rename = "null")]
    Null,
}

impl Default for TransferType {
    fn default() -> TransferType {
        Self::Debit
    }
}

