/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransactionsRemovedWebhook : Fired when transaction(s) for an Item are deleted. The deleted transaction IDs are included in the webhook payload. Plaid will typically check for deleted transaction data several times a day.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransactionsRemovedWebhook {
    /// `TRANSACTIONS`
    #[serde(rename = "webhook_type")]
    pub webhook_type: String,
    /// `TRANSACTIONS_REMOVED`
    #[serde(rename = "webhook_code")]
    pub webhook_code: String,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<crate::models::PlaidError>>,
    /// An array of `transaction_ids` corresponding to the removed transactions
    #[serde(rename = "removed_transactions")]
    pub removed_transactions: Vec<String>,
    /// The `item_id` of the Item associated with this webhook, warning, or error
    #[serde(rename = "item_id")]
    pub item_id: String,
}

impl TransactionsRemovedWebhook {
    /// Fired when transaction(s) for an Item are deleted. The deleted transaction IDs are included in the webhook payload. Plaid will typically check for deleted transaction data several times a day.
    pub fn new(webhook_type: String, webhook_code: String, removed_transactions: Vec<String>, item_id: String) -> TransactionsRemovedWebhook {
        TransactionsRemovedWebhook {
            webhook_type,
            webhook_code,
            error: None,
            removed_transactions,
            item_id,
        }
    }
}


