/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VerificationStatus : The verification status. One of the following:  `\"VERIFIED\"`: The information was successfully verified.  `\"UNVERIFIED\"`: The verification has not yet been performed.  `\"NEEDS_INFO\"`: The verification was attempted but could not be completed due to missing information.  \"`UNABLE_TO_VERIFY`\": The verification was performed and the information could not be verified.  `\"UNKNOWN\"`: The verification status is unknown.

/// The verification status. One of the following:  `\"VERIFIED\"`: The information was successfully verified.  `\"UNVERIFIED\"`: The verification has not yet been performed.  `\"NEEDS_INFO\"`: The verification was attempted but could not be completed due to missing information.  \"`UNABLE_TO_VERIFY`\": The verification was performed and the information could not be verified.  `\"UNKNOWN\"`: The verification status is unknown.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VerificationStatus {
    #[serde(rename = "VERIFIED")]
    VERIFIED,
    #[serde(rename = "UNVERIFIED")]
    UNVERIFIED,
    #[serde(rename = "NEEDS_INFO")]
    NEEDSINFO,
    #[serde(rename = "UNABLE_TO_VERIFY")]
    UNABLETOVERIFY,
    #[serde(rename = "UNKNOWN")]
    UNKNOWN,

}

impl ToString for VerificationStatus {
    fn to_string(&self) -> String {
        match self {
            Self::VERIFIED => String::from("VERIFIED"),
            Self::UNVERIFIED => String::from("UNVERIFIED"),
            Self::NEEDSINFO => String::from("NEEDS_INFO"),
            Self::UNABLETOVERIFY => String::from("UNABLE_TO_VERIFY"),
            Self::UNKNOWN => String::from("UNKNOWN"),
        }
    }
}

impl Default for VerificationStatus {
    fn default() -> VerificationStatus {
        Self::VERIFIED
    }
}




