/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// W2Box12 : Data on the W2 Box 12



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct W2Box12 {
    /// W2 Box 12 code.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// W2 Box 12 amount.
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
}

impl W2Box12 {
    /// Data on the W2 Box 12
    pub fn new() -> W2Box12 {
        W2Box12 {
            code: None,
            amount: None,
        }
    }
}


