/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// W2StateAndLocalWages : W2 state and local wages



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct W2StateAndLocalWages {
    /// State associated with the wage.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    /// State identification number of the employer.
    #[serde(rename = "employer_state_id_number", skip_serializing_if = "Option::is_none")]
    pub employer_state_id_number: Option<String>,
    /// Wages and tips from the specified state.
    #[serde(rename = "state_wages_tips", skip_serializing_if = "Option::is_none")]
    pub state_wages_tips: Option<String>,
    /// Income tax from the specified state.
    #[serde(rename = "state_income_tax", skip_serializing_if = "Option::is_none")]
    pub state_income_tax: Option<String>,
    /// Wages and tips from the locality.
    #[serde(rename = "local_wages_tips", skip_serializing_if = "Option::is_none")]
    pub local_wages_tips: Option<String>,
    /// Income tax from the locality.
    #[serde(rename = "local_income_tax", skip_serializing_if = "Option::is_none")]
    pub local_income_tax: Option<String>,
    /// Name of the locality.
    #[serde(rename = "locality_name", skip_serializing_if = "Option::is_none")]
    pub locality_name: Option<String>,
}

impl W2StateAndLocalWages {
    /// W2 state and local wages
    pub fn new() -> W2StateAndLocalWages {
        W2StateAndLocalWages {
            state: None,
            employer_state_id_number: None,
            state_wages_tips: None,
            state_income_tax: None,
            local_wages_tips: None,
            local_income_tax: None,
            locality_name: None,
        }
    }
}


