/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WalletTransactionCounterparty : An object representing the e-wallet transaction's counterparty



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WalletTransactionCounterparty {
    /// The name of the counterparty
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "numbers")]
    pub numbers: Box<crate::models::WalletTransactionCounterpartyNumbers>,
}

impl WalletTransactionCounterparty {
    /// An object representing the e-wallet transaction's counterparty
    pub fn new(name: String, numbers: crate::models::WalletTransactionCounterpartyNumbers) -> WalletTransactionCounterparty {
        WalletTransactionCounterparty {
            name,
            numbers: Box::new(numbers),
        }
    }
}


