/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WalletTransactionCounterpartyNumbers : The counterparty's bank account numbers



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WalletTransactionCounterpartyNumbers {
    #[serde(rename = "bacs")]
    pub bacs: Box<crate::models::WalletTransactionCounterpartyBacs>,
}

impl WalletTransactionCounterpartyNumbers {
    /// The counterparty's bank account numbers
    pub fn new(bacs: crate::models::WalletTransactionCounterpartyBacs) -> WalletTransactionCounterpartyNumbers {
        WalletTransactionCounterpartyNumbers {
            bacs: Box::new(bacs),
        }
    }
}


