/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Warning : It is possible for an Asset Report to be returned with missing account owner information. In such cases, the Asset Report will contain warning data in the response, indicating why obtaining the owner information failed.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Warning {
    /// The warning type, which will always be `ASSET_REPORT_WARNING`
    #[serde(rename = "warning_type")]
    pub warning_type: String,
    /// The warning code identifies a specific kind of warning. Currently, the only possible warning code is `OWNERS_UNAVAILABLE`, which indicates that account-owner information is not available.
    #[serde(rename = "warning_code")]
    pub warning_code: WarningCode,
    #[serde(rename = "cause")]
    pub cause: crate::models::Cause,
}

impl Warning {
    /// It is possible for an Asset Report to be returned with missing account owner information. In such cases, the Asset Report will contain warning data in the response, indicating why obtaining the owner information failed.
    pub fn new(warning_type: String, warning_code: WarningCode, cause: crate::models::Cause) -> Warning {
        Warning {
            warning_type,
            warning_code,
            cause,
        }
    }
}

/// The warning code identifies a specific kind of warning. Currently, the only possible warning code is `OWNERS_UNAVAILABLE`, which indicates that account-owner information is not available.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WarningCode {
    #[serde(rename = "OWNERS_UNAVAILABLE")]
    OWNERSUNAVAILABLE,
}

impl Default for WarningCode {
    fn default() -> WarningCode {
        Self::OWNERSUNAVAILABLE
    }
}

